; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lcr_meter_stm32f103c8]
platform = ststm32
; board = bluepill_f103c8
board = genericSTM32F103C8
framework = stm32cube
board_build.f_cpu = 72000000L
board_build.ldscript = STM32F103C8TX_FLASH.ld
build_type = debug

upload_protocol = cmsis-dap
upload_flags = -c set CPUTAPID 0x2ba01477 ; Clone reports wrong ID

debug_tool = cmsis-dap
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.system_file = yes
build_flags =
    -Wl,-u,_printf_float ;Reference: https://community.platformio.org/t/sprintf-not-working-on-bluepill/13183